version: '3.8'

services:
  node-exporter:
    image: zhenboyan/rocky_node_exporter:latest
    network_mode: "host" # needs host network
    environment: # change the folloing environment variables
      - MYIP=198.32.43.16
      - PUSHGATEWAY_SERVER=dev2.virnao.com:9091
      - NODE_PORT=9100
    # ports:
    #   - 9100:9100
