version: '3'

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      placement:
        constraints:
          - node.role==manager

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    deploy:
      placement:
        constraints:
          - node.role==manager
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - monitor-net
  
  script_exporter:
    command:
      - '-config.file=/examples/config.yaml'
      - '-web.listen-address=:9469'
    image: 'ricoberger/script_exporter:v2.16.0'
    ports:
      - '9469:9469'
    volumes:
      - './script_exporter/examples:/examples'
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: jdbranham-diagram-panel
    networks:
      - monitor-net

  nginx:
    hostname: nginx
    image: nginx:latest
    ports:
      - 443:443
      - 3000
    volumes:
      - $PWD/nginx/:/etc/nginx/conf.d/ # do not change this line if possible
      - /etc/letsencrypt/live/dev2.virnao.com/cert.pem:/etc/letsencrypt/live/dev2.virnao.com/cert.pem
      - /etc/letsencrypt/live/dev2.virnao.com/privkey.pem:/etc/letsencrypt/live/dev2.virnao.com/privkey.pem
    networks:
      - monitor-net
  
  mainloop:
    image: mainloop:latest
    logging: 
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - /root/.sense-o-auth.yaml:/root/.sense-o-auth.yaml 
      - /etc/letsencrypt/live/dev2.virnao.com/cert.pem:/etc/letsencrypt/live/dev2.virnao.com/cert.pem
      - /etc/letsencrypt/live/dev2.virnao.com/privkey.pem:/etc/letsencrypt/live/dev2.virnao.com/privkey.pem
    networks:
      - monitor-net
    
  # nginx reverse proxy Grafana to https
