version: '3.8'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    network_mode: "host" # grafana needs to be on host network. Find fix to move it to stack
    ports:
      - "3000"
    environment:
      # GF_INSTALL_PLUGINS: jdbranham-diagram-panel
      

  # nginx:
  #   hostname: nginx
  #   image: nginx:latest
  #   # network_mode: "host"
  #   ports:
  #     - 443:443
  #     - 3000
  #   volumes:
  #     - $PWD/nginx/conf/:/etc/nginx/conf.d/
  #     - /etc/grafana/fullchain.pem:/etc/grafana/fullchain.pem
  #     - /etc/grafana/privkey.pem:/etc/grafana/privkey.pem
  #     - /etc/letsencrypt/live/dev2.virnao.com:/etc/letsencrypt/live/dev2.virnao.com
  