{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "End-to-End Flow Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End Flow Topology",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "graph  LR  \n  subgraph  h1  [\"NODENAME1\"]\n  ip{{VLAN: VLANA  -  IP: DATAPLANEIP1}}\n  e(IFNAMEHOST1)\n  end\n  \n  e(IFNAMEHOST1)  ----  sw1s1if[SWITCH2PORT1IF]\n\n  subgraph  sw1  [\"SNMP1NAME Switch\"]\n  subgraph  sw1s1  [\"port\"]\n  sw1s1vlan{{VLAN:  SWITCH1PORT1VLAN}}\n  sw1s1if[SWITCH1PORT1IF]\n  end\n  subgraph  sw1s2  [\"port\"]\n  sw1s2vlan{{VLAN: SWITCH1PORT2VLAN}}\n  sw1s2ifout[SWITCH1PORT1IF]\n  end\n  end\n\n  subgraph  sw2  [\"SNMP2NAME Switch\"]\n  subgraph  sw2s1  [\"port\"]\n  sw2s1vlan{{VLAN: SWITCHBINVLAN}}\n  sw2s1if[SWITCH2PORT1IF]\n  end\n  subgraph  sw2s2  [\"port\"]\n  sw2s2vlan{{VLAN: SWITCH2PORT2VLAN}}\n  sw2s2ifout[SWITCH2PORT2IF]\n  end\n  end\n  \n  sw1s2ifout[SWITCH1PORT2IF]  ----  sw2s1if[SWITCH2PORT1IF]\n  sw2s2ifout[SWITCH2PORT2IF]  ----  e2(IFNAMEHOST2)\n  \n  subgraph  h2  [\"NODENAME2\"]\n  ip2{{VLAN: VLANB  -  IP: DATAPLANEIP2}}  \n  e2(IFNAMEHOST2)\n  end"
   }
  },
  { "title": "Host Flow Summary - NODENAME1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "NODENAME1 General Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "```\nnode name: NODENAME1   if name: IFNAMEHOST1   DATAPLANEIP1   IPHOST1    Vlan: VLANA\n ```"
   }
  },
  {
   "title": "NODENAME1 Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{exported_instance=\"IPHOST1\",device=\"IFNAMEHOST1\"}"
    },
    {
     "expr": "node_uname_info{exported_instance=\"IPHOST1\"}"
    },
    {
     "expr": "node_network_mtu_bytes{exported_instance=\"IPHOST1\",device=\"IFNAMEHOST1\"}"
    }
   ]
  },
  {
   "title": "NODENAME1 - Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOST1\", device=\"IFNAMEHOST1\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOST1\",device=\"IFNAMEHOST1\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMP1NAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "SNMP1NAME Switch Device Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "```\nSwitch: SNMP1NAME   port 1: SWITCH1PORT1IF   port 2: SWITCH1PORT2IF   switch IP: IPSWITCH1\n```"
   }
  },
  {
   "title": "SNMP1NAME Switch Port Info",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(ifIndex{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1PORT1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1PORT2\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1HOST1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1HOST2\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1HOST1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1HOST2\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1HOST1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1HOST2\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1HOST1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1HOST2\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{exported_instance=\"SNMP1HOSTIP\",ifIndex=~\"IFINDEXSWITCH1HOST1|IFINDEXSWITCHHOST1|IFINDEXSWITCH1HOST2\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "SNMP1NAME Switch - Flow Bandwidth - Facing NODENAME1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOST1\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOST1\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMP1NAME Switch - Flow Bandwidth - Facing SWITCH1PORT2IF (SNMP2NAME Switch)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMP2NAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Switch: SNMP2NAME Device Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "```\nSwitch: SNMP2NAME   port 1: SWITCH2PORT1IF   port 2: SWITCH2PORT2IF   switch IP: IPSWITCH2\n ```"
   }
  },
  {
   "title": "SNMP2NAME Switch Port Info",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(ifIndex{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{exported_instance=\"SNMP2HOSTIP\",ifIndex=~\"IFINDEXSWITCH2PORT1|IFINDEXSWITCH2HOSTB|IFINDEXSWITCHHOST2\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "SNMP2NAME Switch - Flow Bandwidth - Facing SWITCH2PORT1IF (SNMP1NAME Switch)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMP2NAME Switch - Flow Bandwidth - Facing NODENAME2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Host Flow Summary - NODENAME2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "NODENAME2 General Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "```\nnode name: NODENAME2   if name: IFNAMEHOST2   DATAPLANEIP2    IPHOST2    Vlan: VLANB\n ```"
   }
  },
  {
   "title": "NODENAME2 Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{exported_instance=\"IPHOST2\",device=\"IFNAMEHOST2\"}"
    },
    {
     "expr": "node_uname_info{exported_instance=\"IPHOST2\"}"
    },
    {
     "expr": "node_network_mtu_bytes{exported_instance=\"IPHOST2\",device=\"IFNAMEHOST2\"}"
    }
   ]
  },
  {
   "title": "NODENAME2 - Flow Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOST2\", device=\"IFNAMEHOST2\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOST2\",device=\"IFNAMEHOST2\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Host Background Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "NODENAME1 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in NODENAME1",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOST1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOST1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOST1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "NODENAME1 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for NODENAME1",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOST1\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOST1\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "NODENAME2 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in NODENAME2",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOST2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOST2\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOST2\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "NODENAME2 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for NODENAME2",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOST2\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOST2\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "NODENAME1 RAM Used",
   "type": "gauge",
   "description": "NODENAME1 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOST1\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOST1\"})"
    }
   ]
  },
  {
   "title": "NODENAME1 SWAP Used",
   "type": "gauge",
   "description": "NODENAME1 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOST1\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOST1\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOST1\"} )) * 100"
    }
   ]
  },
  {
   "title": "NODENAME2 RAM Used",
   "type": "gauge",
   "description": "NODENAME2 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOST2\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOST2\"})"
    }
   ]
  },
  {
   "title": "NODENAME2 SWAP Used",
   "type": "gauge",
   "description": "NODENAME2 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOST2\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOST2\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOST2\"} )) * 100"
    }
   ]
  },
  {
   "title": "NODENAME1 CPU Load",
   "type": "graph",
   "description": "NODENAME1 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOST1\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "NODENAME2 CPU Load",
   "type": "graph",
   "description": "NODENAME2 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOST2\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "NODENAME1 Memory Load",
   "type": "graph",
   "description": "NODENAME1 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOST1\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOST1\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOST1\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOST1\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOST1\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOST1\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOST1\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOST1\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOST1\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOST1\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "NODENAME2 Memory Load",
   "type": "graph",
   "description": "NODENAME2 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOST2\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOST2\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOST2\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOST2\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOST2\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOST2\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOST2\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOST2\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOST2\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOST2\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "NODENAME1 Process Schedule Stats Running/Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOST1\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOST1\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "NODENAME2 Process Schedule Stats Running/Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOST2\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOST2\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "NODENAME1 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOST1\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOST1\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "NODENAME2 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOST2\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOST2\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  { "title": "L2 Debugging", "type": "row", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "ARP Exporter Metrics Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 179 },
   "targets": [
    { "expr": "m_host1_arp_on", "legendFormat": "Host1 ARP On" },
    { "expr": "m_host1_ping_status", "legendFormat": "Host1 Ping Host2" },
    {
     "expr": "m_host1_snmp_mac_status",
     "legendFormat": "Host1 Contains Switch MAC Address"
    },
    {
     "expr": "m_host1_snmp_mac_status2",
     "legendFormat": "Host1 Contains Switch2 MAC Address"
    },
    { "expr": "m_host1_has_host2_arp", "legendFormat": "Host1 Contains Host2 IP" },
    { "expr": "m_host2_arp_on", "legendFormat": "Host2 ARP On" },
    { "expr": "m_host2_ping_status", "legendFormat": "Host2 Ping Host1" },
    {
     "expr": "m_host2_snmp_mac_status",
     "legendFormat": "Host2 Contains Switch MAC Address"
    },
    { "expr": "m_host2_has_host1_arp", "legendFormat": "Host2 Contains Host1 IP" },
    {
     "expr": "m_host2_snmp_mac_status2",
     "legendFormat": "Host2 Contains Switch2 MAC Address"
    }
   ]
  },
  {
   "title": "SNMP Exporter Debugger",
   "type": "state-timeline",
   "description": "SNMP Exporter Metrics Correlation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 180 },
   "targets": [
    { "expr": "m_host1_snmp_on_", "legendFormat": "Host1 SNMP Exporter Running" },
    {
     "expr": "m_switch_host1_mac_",
     "legendFormat": "Switch1 Contains Host1 Mac Address"
    },
    {
     "expr": "SWITCH2_HOSTA_MAC",
     "legendFormat": "Switch2 Contains Host1 Mac Address"
    },
    { "expr": "m_host2_snmp_on_", "legendFormat": "Host2 SNMP Exporter Running" },
    {
     "expr": "m_switch_host2_mac_",
     "legendFormat": "Switch1 Contains Host2 MAC Address"
    },
    {
     "expr": "SWITCH2_HOSTB_MAC",
     "legendFormat": "Switch2 Contains Host2 Mac Address"
    }
   ]
  },
  {
   "title": "Node Exporter Debugger",
   "type": "state-timeline",
   "description": "Node Exporter Status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 181 },
   "targets": [
    { "expr": "m_host1_node_on", "legendFormat": "Host1 Node Exporter" },
    { "expr": "m_host2_node_on", "legendFormat": "Host2 Node Exporter" }
   ]
  }
 ]
}