{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(sysUpTime, job)" } },
   {
    "name": "index",
    "label": "interface",
    "query": {
     "query": "query_result(ifIndex{instance=\"$instance\"})"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "End-to-End Flow Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End Flow Overview",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "graph LR\n subgraph h1 [\"Host 1\"]\n h1ip{{IP: DATAPLANEIPA - VLAN: VLANA}}\n h1e1(IFNAMEHOSTA)\n style h1e1 fill: #50C878\n end\nh1e1 --------- sw1s1if\n subgraph sw1 [\"Switch 1\"]\n subgraph sw1s1 [\"interface 1\"]\n sw1s1vlan{{VLAN: SWITCHAINVLAN SWITCHIF}}\n sw1s1if[NAMEIFSWITCHA]\n style sw1s1if fill: #50C878\n end\n subgraph sw1s2 [\"interface 2\"]\n sw1s2if[NAMEIFSWITCHB]\n sw1s2vlan{{VLAN: SWITCHAOUTVLAN SWITCHIF}}\n style sw1s2if fill: #50C878\n end\n end\n style sw1 fill: #282828\n subgraph h2 [\"Host 2\"]\n h2ip2{{IP: DATAPLANEIPB - VLAN: VLANB}}\n h2e2(IFNAMEHOSTB)\n style h2e2 fill: #50C878\n end\n sw1s2if ---------  h2e2 \n"
   }
  },
  { "title": "Flow Summary - Host 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Host 1 Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "```\n NODENAMEA   IFNAMEHOSTA   DATAPLANEIPA\n ```"
   }
  },
  {
   "title": "Host 1 Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_uname_info{exported_instance=\"IPHOSTA\"}"
    },
    {
     "expr": "node_network_mtu_bytes{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 1 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_receive_packets_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_transmit_packets_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 1 Flow Summary - Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOSTA\", device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Flow Summary - Switch 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Switch 1  Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "```\n Switch 1 (DellS4810)   NAMEIFSWITCHA   NAMEIFSWITCHB   IPSWITCH\n ```"
   }
  },
  {
   "title": "Switch 1 Information (VLAN included)",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(ifIndex{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "VLAN Information",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(ifIndex{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{exported_instance=\"SNMPHOSTIP\",ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "Switch 1 Packets, Bytes Receive/Transmit (VLAN included)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) + irate(ifHCInUcastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) + irate(ifHCInBroadcastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) "
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) + irate(ifHCOutUcastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) + irate(ifHCOutBroadcastPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m]) "
    }
   ]
  },
  {
   "title": "Switch 1 Flow Summary - Bandwidth Graph - Host 1 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOSTA\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOSTA\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 1 Flow Summary - Bandwidth Graph - Host 2 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOSTB\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOSTB\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "VLANs Flow Summary - Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Flow Summary - Host 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Host 2 Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "```\n NODENAMEB   IFNAMEHOSTB   DATAPLANEIPB\n ```"
   }
  },
  {
   "title": "Host 2 Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_uname_info{exported_instance=\"IPHOSTB\"}"
    },
    {
     "expr": "node_network_mtu_bytes{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 2 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_receive_packets_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_transmit_packets_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 2 Flow Summary - Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOSTB\", device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Flow Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Host 1 TCP In / Out",
   "type": "graph",
   "description": "Host 1 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 2 TCP In / Out",
   "type": "graph",
   "description": "Host 2 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 1 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{exported_instance='IPHOSTA'}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 2 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 2",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{exported_instance='IPHOSTB'}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 1 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 2 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 1 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 2 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 1 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 2 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 1 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{exported_instance=\"IPHOSTA\", device=\"IFNAMEHOSTA\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 2 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{exported_instance=\"IPHOSTB\", device=\"IFNAMEHOSTB\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 1 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{exported_instance=\"IPHOSTA\", device=\"IFNAMEHOSTA\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Host 2 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{exported_instance=\"IPHOSTB\", device=\"IFNAMEHOSTB\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  { "title": "Element Background Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Host 1 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTA\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 1 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOSTA\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 2 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTB\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 2 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOSTB\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 1 RAM Used",
   "type": "gauge",
   "description": "Host 1 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOSTA\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"})"
    }
   ]
  },
  {
   "title": "Host 1 SWAP Used",
   "type": "gauge",
   "description": "Host 1 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTA\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 2 RAM Used",
   "type": "gauge",
   "description": "Host 2 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOSTB\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"})"
    }
   ]
  },
  {
   "title": "Host 2 SWAP Used",
   "type": "gauge",
   "description": "Host 2 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTB\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 1 CPU Load",
   "type": "graph",
   "description": "Host 1 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 2 CPU Load",
   "type": "graph",
   "description": "Host 2 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 1 Memory Load",
   "type": "graph",
   "description": "Host 1 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOSTA\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOSTA\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTA\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOSTA\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTA\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 2 Memory Load",
   "type": "graph",
   "description": "Host 2 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOSTB\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOSTB\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTB\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOSTB\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTB\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 1 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 2 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 1 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Host 2 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Switch Total In",
   "type": "singlestat",
   "description": "Switch Dell S4810 Total In ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 188 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch Total Out",
   "type": "singlestat",
   "description": "Switch Dell S4810 Total Out",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 188 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch Max In (Current)",
   "type": "singlestat",
   "description": "Switch Dell S4810 Max In (Current)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 188 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    { "expr": "max(irate(ifHCInOctets{}[5m]))", "legendFormat": "In" }
   ]
  },
  {
   "title": "Switch Max Out (Current)",
   "type": "singlestat",
   "description": "Switch Dell S4810 Max Out (Current)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 188 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch Incoming VLAN Packets",
   "type": "graph",
   "description": "Dell S4810 Switch Incoming VLAN Packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f10IfInVlanPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Outgoing VLAN Packets",
   "type": "graph",
   "description": "Dell S4810 Switch Outgoing VLAN Packets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "f10IfOutVlanPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA|MONITORVLAN1|MONITORVLAN2|MONITORVLAN3\"}"
    }
   ]
  },
  {
   "title": "Host 1 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 2 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 199 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 1 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 2 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 1 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 2 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 219 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 1 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 229 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 2 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 229 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 1 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 239 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  },
  {
   "title": "Host 2 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 239 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  }
 ]
}