{
 "title": "DEBUGTITLE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "End-to-End Flow Overview",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "graph LR\n subgraph h1 [\"Host 1\"]\n h1ip{{IP: DATAPLANEIPA - VLAN: VLANA}}\n h1e1(IFNAMEHOSTA)\n style h1e1 fill: #50C878\n end\nh1e1 --------- sw1s1if\n subgraph sw1 [\"Switch 1\"]\n subgraph sw1s1 [\"interface 1\"]\n sw1s1vlan{{VLAN: VLANA SWITCHIF}}\n sw1s1if[NAMEIFSWITCHA]\n style sw1s1if fill: #50C878\n end\n subgraph sw1s2 [\"interface 2\"]\n sw1s2if[NAMEIFSWITCHB]\n sw1s2vlan{{VLAN: VLANB SWITCHIF}}\n style sw1s2if fill: #50C878\n end\n end\n style sw1 fill: #282828\n subgraph h2 [\"Host 2\"]\n h2ip2{{IP: DATAPLANEIPB - VLAN: VLANB}}\n h2e2(IFNAMEHOSTB)\n style h2e2 fill: #50C878\n end\n sw1s2if ---------  h2e2 \n"
   }
  },
  {
   "title": "Host1 MAC",
   "type": "stat",
   "description": "Host1 MAC address (Obtained from ARP Table)",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    { "expr": "host1_mac" }
   ]
  },
  {
   "title": "Switch MAC",
   "type": "stat",
   "description": "Swtich MAC address (Obtained from ARP Table)",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    { "expr": "switch1_mac" }
   ]
  },
  {
   "title": "Host2 MAC",
   "type": "stat",
   "description": "Host2 MAC Address (Obtained from ARP Table)",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    { "expr": "host2_mac" }
   ]
  },
  {
   "title": "ARP Exporter Debugger",
   "type": "state-timeline",
   "description": "ARP Exporter Metrics Correlation",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "host1_arp_on", "legendFormat": "Host1 ARP On" },
    { "expr": "host1_ping_status", "legendFormat": "Host1 Ping Host2" },
    { "expr": "host1_ping_switch", "legendFormat": "Host1 Ping Switch" },
    {
     "expr": "host1_snmp_mac_status",
     "legendFormat": "Host1 Contains Switch MAC Address"
    },
    { "expr": "host1_has_host2_arp", "legendFormat": "Host1 Contains Host2 IP" },
    { "expr": "host2_arp_on", "legendFormat": "Host2 ARP On" },
    { "expr": "host2_ping_status", "legendFormat": "Host2 Ping Host1" },
    {
     "expr": "host2_snmp_mac_status",
     "legendFormat": "Host2 Contains Switch MAC Address"
    },
    { "expr": "host2_has_host1_arp", "legendFormat": "Host2 Contains Host1 IP" },
    { "expr": "host2_ping_switch", "legendFormat": "Host2 Ping Switch" }
   ]
  },
  {
   "title": "SNMP Exporter Debugger",
   "type": "state-timeline",
   "description": "SNMP Exporter Metrics Correlation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "HOSTA_SNMP_ON", "legendFormat": "Host1 SNMP Exporter Running" },
    {
     "expr": "SWITCH_HOSTA_MAC",
     "legendFormat": "Switch Contains Host1 Mac Address"
    },
    { "expr": "HOSTB_SNMP_ON", "legendFormat": "Host2 SNMP Exporter Running" },
    {
     "expr": "SWITCH_HOSTB_MAC",
     "legendFormat": "Switch Contains Host2 MAC Address"
    }
   ]
  },
  {
   "title": "Node Exporter Debugger",
   "type": "state-timeline",
   "description": "Node Exporter Status",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "host1_node_on", "legendFormat": "Host1 Node Exporter" },
    { "expr": "host2_node_on", "legendFormat": "Host2 Node Exporter" }
   ]
  },
  {
   "title": "Layer 2 Debugging Summary",
   "type": "text",
   "description": "Summary of Layer 2 Debugging Script Results",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 26 },
   "options": {
    "content": "| Action                 |             Status |\n| ----------------------:| ----------------------------:|\n| Debug Script Online | &check; |\n| Ping To Remote Host  | &check; |\n| Remote Host Exists In ARP Table | &check; |\n| Remote Host MAC Address Obtained  | &check; |\n| Remote Host Interface Obtained  | &check; |\n| Remote Host MAC Address Exists in Switch MAC Address | &check; |"
   }
  }
 ]
}