{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(sysUpTime, job)" } },
   {
    "name": "index",
    "label": "interface",
    "query": {
     "query": "query_result(ifIndex{job=~\"$job\",instance=\"$instance\"})"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "End-to-End Flow Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End Flow Overview",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 30, "w": 13, "x": 5, "y": 1 },
   "options": {
    "content": "graph TB\n      subgraph h1 [\"Host 1\"]\n      style h1 fill:#575757\n      ip{{IP: IPHOSTA}}\n      e(IFNAMEHOSTA)\n      end\n      e(IFNAMEHOSTA) ------- s1if1[NAMEIFAIN]\n\n      subgraph s1 [\"Switch 1\"]\n      style s1 fill:#757575\n      s1ip{{IP: IPSWITCHA}}\n      subgraph if [\"Interfaces\"]\n      s1if2[NAMEIFAOUT]\n      s1if1[NAMEIFAIN]\n      end\n      end\n\n      subgraph s3 [\"Switch 2\"]\n      style s3 fill:#757575\n      s3ip{{IP: IPSWITCHB}}\n      subgraph if3 [\"Interfaces\"]\n      s3if1[NAMEIFBIN]\n      s3if2[NAMEIFBOUT]\n      end\n      end\n\n      subgraph s2 [\"Switch 3\"]\n      style s2 fill:#757575\n      s2ip{{IP: IPSWITCHC}}\n      subgraph if2 [\"Interfaces\"]\n      s2if2[NAMEIFCOUT]\n      s2if1[NAMEIFCIN]\n      end\n      end\n      s1if2[NAMEIFAOUT] ------- s3if1[NAMEIFBIN]\n      s3if2[NAMEIFBOUT] ------- s2if1[NAMEIFCIN]\n      s2if2[NAMEIFCOUT] ------- e2(IFNAMEHOSTB)\n      subgraph h2 [\"Host 2\"]\n      style h2 fill:#575757\n      ip2{{IP: IPHOSTB}}\n      e2(IFNAMEHOSTB)\n      end"
   }
  },
  { "title": "Flow Summary - Host 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Host 1 Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "```\n NODENAMEA   IFNAMEHOSTA   DATAPLANEIPA\n ```"
   }
  },
  {
   "title": "Host 1 Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_uname_info{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}"
    },
    {
     "expr": "node_network_mtu_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 1 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_receive_packets_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_transmit_packets_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 1 Flow Summary - Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Flow Summary - Switch 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Switch 1  Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "```\n Switch 1 (DellS4810)   NAMEIFAIN   NAMEIFAOUT   IPSWITCHA\n ```"
   }
  },
  {
   "title": "Switch 1 Information",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(ifIndex{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType_info{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{job=~\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "Switch 1 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\",instance=\"IPSWITCHA\",ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) + irate(ifHCInUcastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) + irate(ifHCInBroadcastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) "
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) + irate(ifHCOutUcastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) + irate(ifHCOutBroadcastPkts{job=\"$job\",instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}[1m]) "
    }
   ]
  },
  {
   "title": "Switch 1 Flow Summary - Bandwidth Graph - Host 1 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHA\", ifIndex=~\"IFNAMESWITCHHOSTA\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHA\", ifIndex=~\"IFNAMESWITCHHOSTA\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 1 Flow Summary - Bandwidth Graph - Switch 2 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Flow Summary - Switch 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Switch 2  Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "```\n Switch 2 (DellS4810)   NAMEIFBIN   NAMEIFBOUT   IPSWITCHB\n ```"
   }
  },
  {
   "title": "Switch 2 Information",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(ifIndex{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType_info{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{job=~\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "Switch 2 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\",instance=\"IPSWITCHB\",ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) + irate(ifHCInUcastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) + irate(ifHCInBroadcastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) "
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) + irate(ifHCOutUcastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) + irate(ifHCOutBroadcastPkts{job=\"$job\",instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}[1m]) "
    }
   ]
  },
  {
   "title": "Switch 2 Flow Summary - Bandwidth Graph - Switch 1 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 2 Flow Summary - Bandwidth Graph - Switch 3 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBOUTGOING\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBOUTGOING\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Flow Summary - Switch 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Switch 3 Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 101 },
   "options": {
    "content": "```\n Switch 2 (DellS4810)   NAMEIFCIN   NAMEIFCOUT   IPSWITCHC\n ```"
   }
  },
  {
   "title": "Switch 3 Information",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(ifIndex{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType_info{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifOperStatus{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifMtu{job=~\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "Switch 3 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m])*8"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) + irate(ifHCInUcastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) + irate(ifHCInBroadcastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) "
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) + irate(ifHCOutUcastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) + irate(ifHCOutBroadcastPkts{job=\"$job\",instance=\"IPSWITCHC\",ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}[1m]) "
    }
   ]
  },
  {
   "title": "Switch 3 Flow Summary - Bandwidth Graph - Switch 2 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHC\", ifIndex=~\"SWITCHCINCOMING\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHC\", ifIndex=~\"SWITCHCINCOMING\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 3 Flow Summary - Bandwidth Graph - Host 2 Facing Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHC\", ifIndex=~\"IFNAMESWITCHHOSTB\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHC\", ifIndex=~\"IFNAMESWITCHHOSTB\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Flow Summary - Host 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Host 2 Flow Summary",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 127 },
   "options": {
    "content": "```\n NODENAMEB   IFNAMEHOSTB   DATAPLANEIPB\n ```"
   }
  },
  {
   "title": "Host 2 Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_info{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_uname_info{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}"
    },
    {
     "expr": "node_network_mtu_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 2 Packets, Bytes Receive/Transmit",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_receive_packets_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_transmit_packets_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 2 Flow Summary - Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\",device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Flow Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Host 1 TCP In / Out",
   "type": "graph",
   "description": "Host 1 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 2 TCP In / Out",
   "type": "graph",
   "description": "Host 2 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 1 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 2 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 2",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 1 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 2 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 1 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 2 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 1 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 2 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 1 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 2 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 1 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Host 2 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 204 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  { "title": "Element Background Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 } },
  {
   "title": "Host 1 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 1 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) /  count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 2 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 2 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) /  count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 1 RAM Used",
   "type": "gauge",
   "description": "Host 1 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} * 100) / node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})"
    }
   ]
  },
  {
   "title": "Host 1 SWAP Used",
   "type": "gauge",
   "description": "Host 1 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) / (node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 2 RAM Used",
   "type": "gauge",
   "description": "Host 2 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} * 100) / node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})"
    }
   ]
  },
  {
   "title": "Host 2 SWAP Used",
   "type": "gauge",
   "description": "Host 2 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) / (node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 1 CPU Load",
   "type": "graph",
   "description": "Host 1 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 2 CPU Load",
   "type": "graph",
   "description": "Host 2 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 1 Memory Load",
   "type": "graph",
   "description": "Host 1 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_MemFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - (node_memory_Cached_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 2 Memory Load",
   "type": "graph",
   "description": "Host 2 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 230 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_MemFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - (node_memory_Cached_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 1 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 2 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 1 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 247 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Host 2 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 247 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 257 } },
  {
   "title": "Switch 1 Total In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 258 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHA\" }[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 1 Total Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 258 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHA\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 1 Max In (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 258 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$job\",  instance=\"IPSWITCHA\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 1 Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 258 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"IPSWITCHA\", job=\"$job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 1 Incoming VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f10IfInVlanPkts{instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 1 Outgoing VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "f10IfOutVlanPkts{instance=\"IPSWITCHA\", ifIndex=~\"SWITCHAOUTGOING|IFNAMESWITCHHOSTA\"}"
    }
   ]
  },
  {
   "title": "Switch 2 Total In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 269 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHB\" }[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 2 Total Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 269 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHB\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 2 Max In (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 269 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$job\",  instance=\"IPSWITCHB\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 2 Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 269 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"IPSWITCHB\", job=\"$job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 2 Incoming VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f10IfInVlanPkts{instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 2 Outgoing VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "f10IfOutVlanPkts{instance=\"IPSWITCHB\", ifIndex=~\"SWITCHBINCOMING|SWITCHBOUTGOING\"}"
    }
   ]
  },
  {
   "title": "Switch 3 Total In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 280 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$job\", instance=\"IPSWITCHC\" }[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 3 Total Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 280 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$job\", instance=\"IPSWITCHC\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 3 Max In (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 280 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$job\",  instance=\"IPSWITCHC\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch 3 Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 280 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"IPSWITCHC\", job=\"$job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch 3 Incoming VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 283 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f10IfInVlanPkts{instance=\"IPSWITCHC\", ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch 3 Outgoing VLAN Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 283 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "f10IfOutVlanPkts{instance=\"IPSWITCHC\", ifIndex=~\"SWITCHCINCOMING|IFNAMESWITCHHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 1 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 291 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 2 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 291 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 1 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 2 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 301 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 1 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 311 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 2 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 311 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 1 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 321 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 2 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 321 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 1 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 331 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  },
  {
   "title": "Host 2 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 331 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  }
 ]
}