{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "End-to-End Flow Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End Flow Topology",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "graph  LR  \n  subgraph  h1  [\"NODENAMEA\"]\n  ip{{VLAN: VLANA  -  IP: DATAPLANEIPA}}\n  e(IFNAMEHOSTA)\n  end\n  \n  e(IFNAMEHOSTA)  ----  sw1s1if[NAMEIFAIN]\n\n  subgraph  sw1  [\"SNMPANAME Switch\"]\n  subgraph  sw1s1  [\"port\"]\n  sw1s1vlan{{VLAN:  SWITCHAINVLAN}}\n  sw1s1if[NAMEIFAIN]\n  end\n  subgraph  sw1s2  [\"port\"]\n  sw1s2vlan{{VLAN: SWITCHAOUTVLAN}}\n  sw1s2ifout[NAMEIFAOUT]\n  end\n  end\n\n  subgraph  sw2  [\"SNMPBNAME Switch\"]\n  subgraph  sw2s1  [\"port\"]\n  sw2s1vlan{{VLAN: SWITCHBINVLAN}}\n  sw2s1if[NAMEIFBIN]\n  end\n  subgraph  sw2s2  [\"port\"]\n  sw2s2vlan{{VLAN: SWITCHBOUTVLAN}}\n  sw2s2ifout[NAMEIFBOUT]\n  end\n  end\n  \n  sw1s2ifout[NAMEIFAOUT]  ----  sw2s1if[NAMEIFBIN]\n  sw2s2ifout[NAMEIFBOUT]  ----  e2(IFNAMEHOSTB)\n  \n  subgraph  h2  [\"NODENAMEB\"]\n  ip2{{VLAN: VLANB  -  IP: DATAPLANEIPB}}  \n  e2(IFNAMEHOSTB)\n  end"
   }
  },
  { "title": "Host Flow Summary - NODENAMEA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "NODENAMEA Node Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "```\nnode name: NODENAMEA   interface name: IFNAMEHOSTA   interface IP: DATAPLANEIPA   node IP: IPHOSTA\n ```"
   }
  },
  {
   "title": "NODENAMEA - Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOSTA\", device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOSTA\",device=\"IFNAMEHOSTA\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMPANAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "SNMPANAME Switch Device Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "```\nSwitch: SNMPANAME   port 1: SWITCHAINCOMING   port 2: SWITCHAOUTGOING   switch IP: IPSWITCHA\n```"
   }
  },
  {
   "title": "SNMPANAME Switch - Flow Bandwidth - Facing NODENAMEA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOSTA\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOSTA\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMPANAME Switch - Flow Bandwidth - Facing SWITCHAOUTGOING",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH1HOSTB\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH1HOSTB\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMPBNAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "SNMPBNAME Switch Device Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "```\nSwitch: SNMPBNAME   port 1: SWITCHAINCOMING   port 2: SWITCHAOUTGOING   switch IP: IPSWITCHB\n```"
   }
  },
  {
   "title": "SNMPBNAME Switch - Flow Bandwidth - Facing SWITCHBINCOMING",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH2HOSTA\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH2HOSTA\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMPBNAME Switch - Flow Bandwidth - Facing NODENAMEB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOSTB\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOSTB\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Host Flow Summary - NODENAMEB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "NODENAMEB Node Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "```\nnode name: NODENAMEB   interface name: IFNAMEHOSTB   interface IP: DATAPLANEIPB    node IP: IPHOSTB\n ```"
   }
  },
  {
   "title": "NODENAMEB - Flow Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOSTB\", device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOSTB\",device=\"IFNAMEHOSTB\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "L2 Debugging", "type": "row", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "NODENAMEA ARP/MAC Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "targets": [
    { "expr": "m_host1_arp_on", "legendFormat": "ARP Exporter Active" },
    { "expr": "m_host1_ping_status", "legendFormat": "ping NODENAMEB" },
    {
     "expr": "m_host1_has_host2_arp",
     "legendFormat": "ARP Table contains NODENAMEB IP Address"
    }
   ]
  },
  {
   "title": "SNMPANAME ARP/MAC Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "targets": [
    { "expr": "m_host1_snmp_on_", "legendFormat": "SNMP Exporter Active" },
    { "expr": "m_switch1_host1_mac_", "legendFormat": "contains NODENAMEA MAC Address" },
    { "expr": "m_switch1_host2_mac_", "legendFormat": "contains NODENAMEB MAC Address" }
   ]
  },
  {
   "title": "SNMPBNAME ARP/MAC Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "targets": [
    { "expr": "m_host2_snmp_on_", "legendFormat": "SNMP Exporter Active" },
    { "expr": "m_switch2_host1_mac_", "legendFormat": "contains NODENAMEA MAC Address" },
    { "expr": "m_switch2_host2_mac_", "legendFormat": "contains NODENAMEB Mac Address" }
   ]
  },
  {
   "title": "NODENAMEB ARP/MAC Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "targets": [
    { "expr": "m_host2_arp_on", "legendFormat": "ARP Exporter Active" },
    { "expr": "m_host2_ping_status", "legendFormat": "ping NODENAMEA" },
    {
     "expr": "m_host2_has_host1_arp",
     "legendFormat": "ARP Table contains NODENAMEA IP Address"
    }
   ]
  },
  { "title": "Host Background Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "NODENAMEA CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in NODENAMEA",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTA\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "NODENAMEA Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for NODENAMEA",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOSTA\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTA\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "NODENAMEB CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in NODENAMEB",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTB\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "NODENAMEB Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for NODENAMEB",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{exported_instance=\"IPHOSTB\"}) /  count(count(node_cpu_seconds_total{exported_instance=\"IPHOSTB\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "NODENAMEA RAM Used",
   "type": "gauge",
   "description": "NODENAMEA Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOSTA\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"})"
    }
   ]
  },
  {
   "title": "NODENAMEA SWAP Used",
   "type": "gauge",
   "description": "NODENAMEA Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTA\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} )) * 100"
    }
   ]
  },
  {
   "title": "NODENAMEB RAM Used",
   "type": "gauge",
   "description": "NODENAMEB Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{exported_instance=\"IPHOSTB\"} * 100) / node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"})"
    }
   ]
  },
  {
   "title": "NODENAMEB SWAP Used",
   "type": "gauge",
   "description": "NODENAMEB Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTB\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} )) * 100"
    }
   ]
  },
  {
   "title": "NODENAMEA CPU Load",
   "type": "graph",
   "description": "NODENAMEA CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTA\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "NODENAMEB CPU Load",
   "type": "graph",
   "description": "NODENAMEB CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exported_instance=\"IPHOSTB\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "NODENAMEA Memory Load",
   "type": "graph",
   "description": "NODENAMEA Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOSTA\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOSTA\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTA\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOSTA\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTA\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTA\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "NODENAMEB Memory Load",
   "type": "graph",
   "description": "NODENAMEB Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_MemFree_bytes{exported_instance=\"IPHOSTB\"} - (node_memory_Cached_bytes{exported_instance=\"IPHOSTB\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTB\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{exported_instance=\"IPHOSTB\"} + node_memory_Buffers_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{exported_instance=\"IPHOSTB\"} - node_memory_SwapFree_bytes{exported_instance=\"IPHOSTB\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "NODENAMEA Process Schedule Stats Running/Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOSTA\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "NODENAMEB Process Schedule Stats Running/Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{exported_instance=\"IPHOSTB\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "NODENAMEA Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOSTA\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "NODENAMEB Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{exported_instance=\"IPHOSTB\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  }
 ]
}