version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    privileged: true
    network_mode: host
    ports:
      - "9091:9091"
    environment:
      - MQTT_LISTENER=9091
      - MQTT_PERSISTENCE=true
      - MQTT_PERSISTENCE_LOCATION=/mosquitto/data/
      - MQTT_LOG_DESTINATION=stdout
      - MQTT_LOG_TYPE=all
      - MQTT_LOG_TIMESTAMP=true
      - MQTT_ALLOW_ANONYMOUS=true
    # volumes:
    #   - ./data:/mosquitto/data
