version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
       - "3000:3000"

    volumes:
       - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #    - ./log/:/mosquitto/log/
    #    - ./data:/mosquitto/data/