version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 9091:9091

volumes:
  data: ~