version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "9091:9091"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log: