###### Clean Slate Environment ######
# hostIP: 172.31.72.189
# ssl_certificate: '/etc/pki/tls/certs/sense-mon_es_net_fullchain.cer' #(fullchain)
# ssl_certificate_key: '/etc/pki/tls/private/sense-mon.key' #(prvikey)

ssl_certificate_key: '/root/sense-o.es.net-ssl/sense-o.key'
ssl_certificate: '/root/sense-o.es.net-ssl/sense-o.crt'
grafana_host: 'http://dev2.virnao.com:3000'
pushgateway: 'http://dev2.virnao.com:9091'
grafana_api_token: "Bearer eyJrIjoiT05BSkJWakFmUkxCaDVadU0wYVhkdEdZc3ZBWng2bGEiLCJuIjoiZCIsImlkIjoxfQ=="