switchNum: 1
dashTitle: "Top Flow Dashboard"
debugTitle: "Top Flow L2 Debugging Dashboard"
flow: " flow 1 "
hostIP: 198.32.43.16 # example 198.32.43.16
# The DNS of the host which is running the Grafana container
grafanaHostIP: 'dev2.virnao.com'
grafanaPort: 3000 # Do not change unless container mapping change
pushgatewayPort: 9091 # Do not change unless container mapping change
grafanaAPIToken: "CONFIG"
configFile: "config.yml"

# Host 1
hostA:
  IP: 198.32.43.16
  interfaceName: 'ens2f0np0.1000'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/27'
    ifVlan: 'Vlan 1000'

# Host 2
hostB:
  IP: 198.32.43.15
  interfaceName: 'ens2f0.1000'
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/31'
    ifVlan: 'Vlan 1000'

switchData:
  job_name: 'snmp1'
  SNMPHostIP: 198.32.43.16
  target: 172.16.1.1
  # switch if format: " - IF: optional" 
  switchif: "" # optional
  portIn:
    ifName: 'hundredGigE 1/27'
    vlan: 1000
    ifVlan: 'Vlan 1000'
  portOut:
    ifName: 'hundredGigE 1/31'
    vlan: 1000
    ifVlan: 'Vlan 1000'

# TCP/ARP Data
tcpMetrics:
  port: 9191
  job_name: 'tcpmetrics'

arpMetrics:
  port: 9192
  job_name: 'arpmetrics'