###### Clean Slate Environment ######
switchNum: 1
hostIP:  # 198.32.43.16
# The DNS of the host which is running the Grafana container
grafanaHostIP: ''
pushgatewayPort: 9091 # Do not change unless container mapping change
hostA: # Host 1
  IP:
hostB: # Host 2
  IP: 
