apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f snmp-docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: snmp-exporter
  name: snmp-exporter
spec:
  ports:
    - name: "9116"
      port: 9116
      targetPort: 9116
  selector:
    io.kompose.service: snmp-exporter
status:
  loadBalancer: {}
