## SECTION 1 GENERAL INFORMATION ##
switchNum: 2
dashTitle: "Multi Switch Flow Dashboard"
debugTitle: "Multi Switch Flow L2 Debugging Dashboard"
flow: " flow 2 "
hostIP: 198.124.151.8 # example 198.32.43.16
# The DNS of the host which is running the Grafana container
grafanaHostIP: 'sense-mon.es.net'
grafanaPort: 3000 # Do not change unless container mapping change
pushgatewayPort: 9091 # Do not change unless container mapping change
grafanaAPIToken: "CONFIG"
configFile: "multiconfig.yml"

hostA: # Host 1
  IP: 198.32.43.16
  interfaceName: 'ens2f0np0.1000'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/27'
    ifVlan: 'Vlan 1000'
    order: 1

hostB: # Host 2
  IP: 198.32.43.15
  interfaceName: 'ens2f0.1000'
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/31'
    ifVlan: 'Vlan 1000'
    order: 6

## SECTION 2 SWITCH INFORMATION ##
switchDataA:
  job_name: 'snmp1'
  SNMPHostIP: 198.32.43.16
  target: 172.16.1.1
  # switch if format: " - IF: optional" 
  switchif: "" # optional
  portIn:
    ifName: 'hundredGigE 1/27'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 2

  portOut:
    ifName: 'hundredGigE 1/31'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 3

switchDataB:
  job_name: 'snmp2'
  SNMPHostIP: 198.32.43.16
  target: 172.16.1.1
  # switch if format: " - IF: optional" 
  switchif: "" # optional
  portIn:
    ifName: 'hundredGigE 1/27'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 4
  portOut:
    ifName: 'hundredGigE 1/31'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 5

## SECTION 3 TCP and ARP (possible more in the future) ##
arpMetrics:
  port: 9192
  job_name: 'arpmetrics'

tcpMetrics:
  port: 9191
  job_name: 'tcpmetrics'