## SECTION 1 GENERAL INFORMATION ##
title: "Multi Switch Flow Dashboard"
flow: " flow 2 "
hostIP: 198.124.151.8 
grafana_host: 'sense-mon.es.net:3000'
pushgateway: 'sense-mon.es.net:9091'
grafanaAPIToken: "CONFIG"

host: # Host 1
  num: 2 # Number of hosts
  
  - institute: 'caltech'
    node: 'sdn-dtn-2-10.ultralight.org'
    ip: '10.251.86.10'
    interface: 
      - name: 'ens2f0np0.3911'
        peer: 
           node:
           port: 
      - name: ''
        peer: ...
    interface_ip: '10.251.86.10/24'
    vlan: 'not_used'
    num_port: 1
    port1: 
      if_name: 'hundredGigE 1/31'
      vlan: '3911'

  - institute: 'ucsd_cluster'
    node: 'k8s-gen4-01.sdsc.optiputer.net'
    ip: '10.251.86.14'
    interface: 'vlan.3911'
      port1:
        if_name: 'etp27'
        vlan: '3911'
    interface_ip: '10.251.86.14'
    vlan: '3911'
    num_port: 1

## SECTION 2 SWITCH INFORMATION ##
switch:
  num: 3 # Number of switches
  # could also do an array style
  switch1:    
    institute: 'caltech'
    running_from_ip: '10.251.86.10'
    target: 172.16.1.1
    num_port: 2
    port1:
      if_name: 'hundredGigE 1/31'
      vlan: '3911'
    port2:
      if_name: 'Port-channel 103'
      vlan: '3911'
      peer: 
        node: switch2
        port: port1

  switch2:
    institute: 'ucsd_cluster'
    running_from_ip: '10.251.86.14'
    target: 132.249.2.46
    num_port: 2
    port1:
      if_name: 'PortChannel501'
      vlan: '3911'
      peer: 
        node: switch1
        port: port2
    port2:
      if_name: 'etp27'
      vlan: '3911'   
  
  switch3:
    job_name: 'ucsd_cluster'
    running_from_ip: '10.251.86.14'
    target: 132.249.2.46
    num_port: 2
    port1:
      if_name: 'PortChannel501'
      vlan: '3911'
    port2:
      if_name: 'etp27'
      vlan: '3911'  
