apiVersion: v1
data:
    rtmon-yaml: IyBTbGVlcCB0aW1lciBiZXR3ZWVuIHJ1bnMKc2xlZXBfdGltZXI6IDMwCiMgV29yayBkaXIgZm9yIHRlbXAgZmlsZXMgKGFwaSBkaXJlY3RvcnkpLiBEZWZhdWx0IC9zcnYKd29ya2RpcjogJy9zcnYvJwoKZ3JhZmFuYV9ob3N0OiAnaHR0cHM6Ly9hdXRvZ29sZS1ncmFmYW5hLm5ycC1uYXV0aWx1cy5pbycKZ3JhZmFuYV9hcGlfa2V5OiAnUkVQTEFDRV9NRScKCnRlbXBsYXRlX3BhdGg6ICcvZXRjL3J0bW9uL3RlbXBsYXRlcycKdGVtcGxhdGVfdGFnOiAnVjAuMDEnCgpkYXRhX3NvdXJjZXM6CiAgZ2VuZXJhbDogUHJvbWV0aGV1cwogIHJlYWx0aW1lOiBQcm9tZXRoZXVzUlQKCgpzZW5zZV9lbmRwb2ludHM6CiAgInNlbnNlLW8uZXMubmV0IjogIi9ldGMvc2Vuc2Utby1hdXRoLXByb2QueWFtbCIKICAic2Vuc2Utby1kZXYuZXMubmV0IjogIi9ldGMvc2Vuc2Utby1hdXRoLnlhbWwiCgp0ZW1wbGF0ZV9saW5rczoKICAgIC0gdGl0bGU6ICdBbGwgTm9kZSBNb25pdG9yaW5nJwogICAgICB1cmw6ICdodHRwczovL2F1dG9nb2xlLWdyYWZhbmEubnJwLW5hdXRpbHVzLmlvL2QvRDd4T3hpbTR6L2Z1bGwtZHRuLW1vbml0b3JpbmctdmFyaWFibGU/b3JnSWQ9MSZyZWZyZXNoPTFtJwogICAgLSB0aXRsZTogJ0FsbCBTd2l0Y2hlcyBNb25pdG9yaW5nJwogICAgICB1cmw6ICdodHRwczovL2F1dG9nb2xlLWdyYWZhbmEubnJwLW5hdXRpbHVzLmlvL2QvMUo5WnoxbVd6L2Z1bGwtc3dpdGNoLW1vbml0b3JpbmctdmFyaWFibGU/b3JnSWQ9MSZyZWZyZXNoPTFtJwo=
    sense-o-auth-yaml: QVVUSF9FTkRQT0lOVDogaHR0cHM6Ly9zZW5zZS1vLmVzLm5ldDo4NTQzL2F1dGgvcmVhbG1zL1N0YWNrVi9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC90b2tlbgpBUElfRU5EUE9JTlQ6IGh0dHBzOi8vc2Vuc2Utby1kZXYuZXMubmV0Ojg0NDMvU3RhY2tWLXdlYi9yZXN0YXBpCkNMSUVOVF9JRDogU3RhY2tWClVTRVJOQU1FOiBSRVBMQUNFTUUKUEFTU1dPUkQ6IFJFUExBQ0VNRQpTRUNSRVQ6IFJFUExBQ0VNRQp2ZXJpZnk6IFRydWU=
    sense-o-auth-prod-yaml: QVVUSF9FTkRQT0lOVDogaHR0cHM6Ly9zZW5zZS1vLmVzLm5ldDo4NTQzL2F1dGgvcmVhbG1zL1N0YWNrVi9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC90b2tlbgpBUElfRU5EUE9JTlQ6IGh0dHBzOi8vc2Vuc2Utby5lcy5uZXQ6ODQ0My9TdGFja1Ytd2ViL3Jlc3RhcGkKQ0xJRU5UX0lEOiBSRVBMQUNFTUUKVVNFUk5BTUU6IFJFUExBQ0VNRQpQQVNTV09SRDogUkVQTEFDRU1FClNFQ1JFVDogUkVQTEFDRU1FCnZlcmlmeTogVHJ1ZQo=
kind: Secret
metadata:
    name: secret-rtmon
    namespace: opennsa
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        run: run-rtmon
    name: sense-rtmon
    namespace: opennsa
spec:
    replicas: 1
    selector:
        matchLabels:
            run: run-rtmon
    template:
        metadata:
            labels:
                run: run-rtmon
        spec:
            containers:
                - image: sdnsense/sense-rtmon:latest
                  imagePullPolicy: Always
                  name: pod-rtmon
                  resources:
                    limits:
                        cpu: 1
                        memory: 2Gi
                    requests:
                        cpu: 1
                        memory: 2Gi
                  volumeMounts:
                    - mountPath: /etc/rtmon.yaml
                      name: secret-rtmon
                      readOnly: true
                      subPath: rtmon.yaml
                    - mountPath: /etc/sense-o-auth.yaml
                      name: secret-rtmon
                      readOnly: true
                      subPath: sense-o-auth.yaml
                    - mountPath: /etc/sense-o-auth-prod.yaml
                      name: secret-rtmon
                      readOnly: true
                      subPath: sense-o-auth-prod.yaml
                    - mountPath: /etc/grid-security/hostcert.pem
                      name: siterm-cert
                      readOnly: true
                      subPath: cert.pem
                    - mountPath: /etc/grid-security/hostcert.pem
                      name: siterm-key
                      readOnly: true
                      subPath: key.pem
            volumes:
                - name: secret-rtmon
                  secret:
                    defaultMode: 420
                    items:
                        - key: rtmon-yaml
                          path: rtmon.yaml
                        - key: sense-o-auth-yaml
                          path: sense-o-auth.yaml
                        - key: sense-o-auth-prod-yaml
                          path: sense-o-auth-prod.yaml
                    secretName: secret-rtmon
                - name: siterm-cert
                  secret:
                    secretName: autogole-monitoring
                    items:
                    - key: siterm-cert
                      path: cert.pem
                    defaultMode: 0644
                - name: siterm-key
                  secret:
                    secretName: autogole-monitoring
                    items:
                    - key: siterm-key
                      path: key.pem
                    defaultMode: 0644
