version: '3.8'

services:
  node-exporter:
    image: zhenboyan/rocky_snmp_exporter:latest
    network_mode: "host" # in the future not host option, 
    environment: # change the folloing environment variables
      - MYIP=198.32.43.16
      - PUSHGATEWAY_SERVER=dev2.virnao.com:9091
      - SWITCH_TARGET=172.16.1.1
      - PRIVATE_MIB=dell
      - COMMUNITY_STRING=
      # COMMUNITY_STRING should not be pushed to github
    ports:
      - 9116:9116
