# Number of switches
switchNum: 2
# Grafana Dashboard Title   
dashTitle: "Multi Switch Flow Dashboard"
# L2 Debugging Dashboard Title
debugTitle: "Multi Switch Flow L2 Debugging Dashboard"
# Flow number
flow: " flow 1 "
# vlan flow
vlan_to_switch: 1000
# This host's IP address
hostIP: 198.32.43.16
# Prometheus Port
prometheusPort: 9090
# The IP of the host which is running the Grafana container
grafanaHostIP: 'dev2.virnao.com'
# The port which the Grafana container is listening on
# Default is 3000
grafanaPort: 3000
# Grafana API Token
grafanaAPIToken: "Bearer eyJrIjoiN3M2UkFBODdqdFJ2V3A0SUxpMlI5S2g2QktvdjM2cUwiLCJuIjoiMDgvMTIiLCJpZCI6MX0="
# if HTTPS enabled and certified during the install process
# encrypted: False
encrypted: True
# indicate the config file that's used
configFile: "multiconfig.yml"

# Host 1 Specifics 
hostA:
  IP: 198.32.43.16
  interfaceName: 'enp4s0f0'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/46'
    ifVlan: 'Vlan 1000'

# Host 2 Specifics
hostB:
  IP: 198.32.43.15
  interfaceName: 'enp4s0f0'
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/45'
    ifVlan: 'Vlan 1000'

# Prometheus source specifics

switchDataA:
  job_name: 'snmp1'
  # The IP of the host which is running the SNMP Exporter container
  SNMPHostIP: 198.32.43.16
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  target: 172.16.1.1
  # switch if format: " - IF: optional"
  switchif: ""
  #if-mib and F10-IF-EXTENSION-MIB
  params: ['if_mib']
  portIn: 
    ifName: 'TenGigabitEthernet 0/43'
    vlan: 1000
    ifVlan: 'Vlan 1000'
  portOut: 
    ifName: 'TenGigabitEthernet 0/8'
    vlan: 1000
    ifVlan: 'Vlan 1000'


switchDataB:
  job_name: 'snmp2'
  # The IP of the host which is running the SNMP Exporter container
  SNMPHostIP: 198.32.43.16
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  target: 172.16.1.1
  # switch if format: " - IF: optional"
  switchif: ""
  #if-mib and F10-IF-EXTENSION-MIB
  params: ['if_mib2']
  portIn: 
    ifName: 'TenGigabitEthernet 0/43'
    vlan: 1000
    ifVlan: 'Vlan 1000'
  portOut: 
    ifName: 'TenGigabitEthernet 0/8'
    vlan: 1000
    ifVlan: 'Vlan 1000'

snmpMetricsA:
  # IP address of switch to configure
  switchIP: 172.16.1.1
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  # OIDs to scrape
  oids: [dot1dTpFdbAddress, ifMIB, ifMtu, ifName, ifOperStatus, ifPhysAddress, ifIndex, ifType, dellNetIfInVlanPkts, f10IfOutVlanPkts]
  communityString: "mgmt_hep"
  # Scrape timeout default is 5s
  scrapeTimeout: 5s
  # Max retries default is 3
  retries: 3

snmpMetricsB:
  # IP address of switch to configure
  switchIP: 172.16.1.1
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  # OIDs to scrape
  oids: [dot1dTpFdbAddress, ifMIB, ifMtu, ifName, ifOperStatus, ifPhysAddress, ifIndex, ifType, dellNetIfInVlanPkts, f10IfOutVlanPkts]
  communityString: "mgmt_hep"
  # Scrape timeout default is 5s
  scrapeTimeout: 5s
  # Max retries default is 3
  retries: 3

# TCP/ARP Data
tcpMetrics:
  port: 9191 # Site
  job_name: 'tcpmetrics'
  # Collect all packets continuously over the scrape interval
  # Not recommended for general use cases, but provides additional information if set to True
  # Defaults to False, collects the most recent burst (1 second's worth of data) at the current scrape interval
  continuousCollect: False
  scrapeDuration: 900
  scrapeInterval: 30

arpMetrics:
  port: 9192
  job_name: 'arpmetrics'
  scrapeDuration: 900
  scrapeInterval: 30