# Number of switches
switchNum: 2
# Grafana Dashboard Title   
dashTitle: "Multi Switch Flow Dashboard"
# L2 Debugging Dashboard Title
debugTitle: "Multi Switch Flow L2 Debugging Dashboard"
# Flow number
flow: " flow 1 "
# vlan flow
vlan_to_switch: 1000
# This host's IP address
hostIP: 198.32.43.16
# Prometheus Port
prometheusPort: 9090
# The IP of the host which is running the Grafana container
grafanaHostIP: 'dev2.virnao.com'
# The port which the Grafana container is listening on
# Default is 3000
grafanaPort: 3000
# Grafana API Token
grafanaAPIToken: "Bearer eyJrIjoiNWYwWEFzVTRUUHQ5TWg3cVBUdHpMV01PREo1aWJmeUkiLCJuIjoiMDcvMTQiLCJpZCI6MX0="
# if HTTPS enabled and certified during the install process
# encrypted: False
encrypted: True
# indicate the config file that's used
configFile: "multiconfig.yml"
ifVlan1: 'Vlan 1000'
ifVlan2: 'Vlan 1000'
ifVlan3: 'Vlan 1000'

# Host 1 Specifics 
hostA:
  IP: 198.32.43.16
  interfaceName: 'enp4s0f0'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/46'
    ifIndex: 1054468

# Host 2 Specifics
hostB:
  IP: 198.32.43.15
  interfaceName: 'enp4s0f0'
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort: 
    ifName: 'TenGigabitEthernet 0/45'
# Prometheus source specifics

switchDataA:
  job_name: 'snmp1'
  # The IP of the host which is running the SNMP Exporter container
  SNMPHostIP: 198.32.43.16
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  target: 172.16.1.1
  # switch if format: " - IF: optional"
  switchif: ""
  #if-mib and F10-IF-EXTENSION-MIB
  params: ['if_mib']
  portIn: 
    ifName: 'TenGigabitEthernet 0/43'
    vlan: 1000
    ifVlan: 'Vlan 1000'
  portOut: 
    ifName: 'TenGigabitEthernet 0/8'
    vlan: 1000
    ifVlan: 'Vlan 1000'


switchDataB:
  job_name: 'snmp2'
  # The IP of the host which is running the SNMP Exporter container
  SNMPHostIP: 198.32.43.16
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  target: 172.16.1.14
  # switch if format: " - IF: optional"
  switchif: ""
  #if-mib and F10-IF-EXTENSION-MIB
  params: ['if_mib2']
  portIn: 
    ifName: 'TenGigabitEthernet 0/43'
    vlan: 1000
    ifVlan: 'Vlan 1000'
  portOut: 
    ifName: 'TenGigabitEthernet 0/8'
    vlan: 1000
    ifVlan: 'Vlan 1000'

snmpMetricsA:
  # IP address of switch to configure
  switchIP: 172.16.1.1
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  # OIDs to scrape
  oids: [1.3.6.1.2.1.17.4.3.1.1, 1.3.6.1.2.1.31, 1.3.6.1.2.1.2.2.1.4, 1.3.6.1.2.1.2.2.1.8, 1.3.6.1.2.1.2.2.1.6, 1.3.6.1.2.1.2.2.1.1, 1.3.6.1.2.1.2.2.1.3, 1.3.6.1.4.1.6027.3.11.1.2.1.1.1, 1.3.6.1.4.1.6027.3.11.1.2.1.1.13]
  communityString: "COMMUNITYSTRING"
  # Scrape timeout default is 5s
  scrapeTimeout: 5s
  # Max retries default is 3
  retries: 3

snmpMetricsB:
  # IP address of switch to configure
  switchIP: 172.16.1.4
  # Scrape interval/duration time
  scrapeInterval: 15s
  scrapeDuration: 5h
  # OIDs to scrape
  oids: [1.3.6.1.2.1.17.4.3.1.1, 1.3.6.1.2.1.31, 1.3.6.1.2.1.2.1]
  # SNMP community read string
  communityString: "COMMUNITYSTRING"
  # Scrape timeout default is 5s
  scrapeTimeout: 5s
  # Max retries default is 3
  retries: 3

# TCP/ARP Data
tcpMetrics:
  port: 9191
  job_name: 'tcpmetrics'
  # Collect all packets continuously over the scrape interval
  # Not recommended for general use cases, but provides additional information if set to True
  # Defaults to False, collects the most recent burst (1 second's worth of data) at the current scrape interval
  continuousCollect: False
  # How long to scrape host-level data (in seconds)
  scrapeDuration: 900
  # Scrape interval duration (in seconds)
  scrapeInterval: 30
  # Receiving end IP Address, where pushgateway located
  receiverIP: 'localhost' #change it

arpMetrics:
  port: 9192
  job_name: 'arpmetrics'
  # How long to scrape host-level data (in seconds)
  scrapeDuration: 900
  # Scrape interval duration (in seconds)
  scrapeInterval: 30
  # Receiving end IP Address, where pushgateway located
  receiverIP: 'localhost' #change it