# Define a custom YAML tag for IPv4 addresses
# %TAG !ipv4! tag:yaml.org,2002:
# ---

## Section 1 General Dashboard information
dashboard:
  title: "Multi Switch Flow Dashboard"
  flow: "flow 2"
  dashboard_host_ip: 198.124.151.8
  grafana_host: 'sense-mon.es.net:3000'
  pushgateway: 'sense-mon.es.net:9091'
  grafana_api_token: "CONFIG"

## Section 2 Hosts & Switches all under nodes
node:
  # Define a host with two interfaces and a peer to a switch
  - name: 'sdn-dtn-2-10.ultralight.org'
    type: 'host'
    interface:
      - &interface1
        name: 'ens2f0np0.3911'
        ip: 10.251.86.10
        vlan: 'not used'
      - &interface2
        name: 'hundredGigE 1/31'
        vlan: 'not used'
    peer:
      - from: *interface2
        to: [*interface3]

  # Define a switch with two interfaces and two peers to other nodes
  - name: 'Caltech LRT-SDN-R02-Dell-Z9100'
    type: 'switch'
    interface:
      - &interface3
        name: 'hundredGigE 1/31'
        ip: 172.16.1.1
        vlan: 'not used'
      - &interface4
        name: 'Port-channel 103'
        vlan: 'not used'
    peer:
      - from: *interface3
        to: [*interface2]
      - from: *interface4
        to: [*interface5]

  # Define another switch with two interfaces and two peers to other nodes
  - name: 'UCSD SN3700'
    type: 'switch'
    interface:
      - &interface5
        name: 'PortChannel501'
        vlan: 'not used'
      - &interface6
        name: 'etp28'
        vlan: 'not used'
    peer:
      - from: *interface5
        to: [*interface4]
      - from: *interface6
        to: [*interface8]

  # Define another host with two interfaces and a peer to a switch
  - name: 'k8s-gen4-02.sdsc.optiputer.net'
    type: 'host'
    interface:
      - &interface7
        name: 'vlan.3911'
        ip: 10.251.86.12
        vlan: 'not used'
      - &interface8
        name: 'etp28'
        vlan: 'not used'
    peer:
      - from: *interface8
        to: [*interface6]