version: '3.8'

services:
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/snmp2.yml:/etc/snmp_exporter/snmp2.yml
    network_mode: "host"
    ports:
      - 9117:9117
  
