version: '3.8'

services:
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    # network_mode: "host" # in the future not host option, 
    ports:
      - 9116:9116 # 9117:9116 external:internal