version: '3.8'
# do no delete
services:
  snmp-exporter:
    image: prom/snmp-exporter
    volumes:
      - ../SNMPExporter/snmp1.yml:/etc/snmp_exporter/snmp1.yml
    # network_mode: "host" # in the future not host option, 
    ports:
      - 9116:9116 # 9117:9116 external:internal