version: '3.8'

services:
  tcp-exporter:
    image: tcp_exporter
    network_mode: "host"
    restart: always
    volumes:
      - ../../config/config.yml:/etc/tcp_exporter/tcp.yml
    ports:
      - 9191:9191
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

# please do not change the position of volumes. It's dynamically built line 8 (count from 0)
