{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "End-to-End Flow Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "End-to-End Flow Topology",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "graph  LR  \n  subgraph  h1  [\"NODENAME1\"]\n  ip{{VLAN: VLANA  -  IP: DATAPLANEIP1}}\n  e(IFNAMEHOST1)\n  end\n  \n  e(IFNAMEHOST1)  ----  sw1s1if[SWITCH2PORT1IF]\n\n  subgraph  sw1  [\"SNMP1NAME Switch\"]\n  subgraph  sw1s1  [\"port\"]\n  sw1s1vlan{{VLAN:  SWITCH1PORT1VLAN}}\n  sw1s1if[SWITCH1PORT1IF]\n  end\n  subgraph  sw1s2  [\"port\"]\n  sw1s2vlan{{VLAN: SWITCH1PORT2VLAN}}\n  sw1s2ifout[SWITCH1PORT1IF]\n  end\n  end\n\n  subgraph  sw2  [\"SNMP2NAME Switch\"]\n  subgraph  sw2s1  [\"port\"]\n  sw2s1vlan{{VLAN: SWITCHBINVLAN}}\n  sw2s1if[SWITCH2PORT1IF]\n  end\n  subgraph  sw2s2  [\"port\"]\n  sw2s2vlan{{VLAN: SWITCH2PORT2VLAN}}\n  sw2s2ifout[SWITCH2PORT2IF]\n  end\n  end\n  \n  sw1s2ifout[SWITCH1PORT2IF]  ----  sw2s1if[SWITCH2PORT1IF]\n  sw2s2ifout[SWITCH2PORT2IF]  ----  e2(IFNAMEHOST2)\n  \n  subgraph  h2  [\"NODENAME2\"]\n  ip2{{VLAN: VLANB  -  IP: DATAPLANEIP2}}  \n  e2(IFNAMEHOST2)\n  end"
   }
  },
  { "title": "Host Flow Summary - NODENAME1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "NODENAME1 General Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "```\nnode name: NODENAME1   if name: IFNAMEHOST1   DATAPLANEIP1   IPHOST1    Vlan: VLANA\n ```"
   }
  },
  {
   "title": "NODENAME1 - Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOST1\", device=\"IFNAMEHOST1\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOST1\",device=\"IFNAMEHOST1\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMP1NAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "SNMP1NAME Switch Device Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "```\nSwitch: SNMP1NAME   port 1: SWITCH1PORT1IF   port 2: SWITCH1PORT2IF   switch IP: IPSWITCH1\n```"
   }
  },
  {
   "title": "SNMP1NAME Switch - Flow Bandwidth - Facing NODENAME1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOST1\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOST1\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMP1NAME Switch - Flow Bandwidth - Facing SWITCH1PORT2IF (SNMP2NAME Switch)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - SNMP2NAME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Switch: SNMP2NAME Device Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "```\nSwitch: SNMP2NAME   port 1: SWITCH2PORT1IF   port 2: SWITCH2PORT2IF   switch IP: IPSWITCH2\n ```"
   }
  },
  {
   "title": "SNMP2NAME Switch - Flow Bandwidth - Facing SWITCH2PORT1IF (SNMP1NAME Switch)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCH1HOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "SNMP2NAME Switch - Flow Bandwidth - Facing NODENAME2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"IFINDEXSWITCHHOST2\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"IFINDEXSWITCHHOST2\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  { "title": "Host Flow Summary - NODENAME2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "NODENAME2 General Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "```\nnode name: NODENAME2   if name: IFNAMEHOST2   DATAPLANEIP2    IPHOST2    Vlan: VLANB\n ```"
   }
  },
  {
   "title": "NODENAME2 - Flow Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"IPHOST2\", device=\"IFNAMEHOST2\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"IPHOST2\",device=\"IFNAMEHOST2\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  }
 ]
}