apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f arp-docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: arp-exporter
  name: arp-exporter
spec:
  ports:
    - name: "9192"
      port: 9192
      targetPort: 9192
  selector:
    io.kompose.service: arp-exporter
status:
  loadBalancer: {}
