{
 "title": "DEBUGTITLE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "End-to-End Flow Overview",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "graph  LR  \n  subgraph  h1  [\"Host 1\"]\n  ip{{VLAN: VLANA  -  IP: DATAPLANEIPA}}\n  e(IFNAMEHOSTA)\n  end\n  \n  e(IFNAMEHOSTA)  ----  sw1s1if[NAMEIFAIN]\n\n  subgraph  sw1  [\"Switch 1\"]\n  subgraph  sw1s1  [\"interface  1\"]\n  sw1s1vlan{{VLAN:  SWITCHAINVLAN}}\n  sw1s1if[NAMEIFAIN]\n  end\n  subgraph  sw1s2  [\"interface 2\"]\n  sw1s2vlan{{VLAN: SWITCHAOUTVLAN}}\n  sw1s2ifout[NAMEIFAOUT]\n  end\n  end\n\n  subgraph  sw2  [\"Switch  2\"]\n  subgraph  sw2s1  [\"interface 1\"]\n  sw2s1vlan{{VLAN: SWITCHBINVLAN}}\n  sw2s1if[NAMEIFBIN]\n  end\n  subgraph  sw2s2  [\"interface 2\"]\n  sw2s2vlan{{VLAN: SWITCHBOUTVLAN}}\n  sw2s2ifout[NAMEIFBOUT]\n  end\n  end\n  \n  sw1s2ifout[NAMEIFAOUT]  ----  sw2s1if[NAMEIFBIN]\n  sw2s2ifout[NAMEIFBOUT]  ----  e2(IFNAMEHOSTB)\n  \n  subgraph  h2  [\"Host 2\"]\n  ip2{{VLAN: VLANB  -  IP: DATAPLANEIPB}}  \n  e2(IFNAMEHOSTB)\n  end"
   }
  },
  {
   "title": "Remote Host IP",
   "type": "stat",
   "description": "Remote Host IP",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remote_host_mac" }
   ]
  },
  {
   "title": "Remote Host Interface",
   "type": "stat",
   "description": "Remote Host Interface (Obtained from ARP Table)",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remote_host_mac" }
   ]
  },
  {
   "title": "Remote Host MAC Address",
   "type": "stat",
   "description": "Remote Host MAC Address (Obtained from ARP Table)",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remote_host_mac" }
   ]
  },
  {
   "title": "Network Element Count",
   "type": "gauge",
   "description": "Number of Network Elements in the Flow",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m_network_element_count" }
   ]
  },
  {
   "title": "Network Element 1 IP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m_network_element_ip_one" }
   ]
  },
  {
   "title": "Network Element 2 IP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m_network_element_ip_one" }
   ]
  },
  {
   "title": "ARP Exporter Metrics Correlation",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "m_host1_arp_on", "legendFormat": "Host1 ARP On" },
    { "expr": "m_host1_ping_status", "legendFormat": "Host1 Ping Host2" },
    {
     "expr": "m_host1_snmp_mac_status",
     "legendFormat": "Host1 Contains Switch MAC Address"
    },
    {
     "expr": "m_host1_snmp_mac_status2",
     "legendFormat": "Host1 Contains Switch2 MAC Address"
    },
    { "expr": "m_host1_has_host2_arp", "legendFormat": "Host1 Contains Host2 IP" },
    { "expr": "m_host2_arp_on", "legendFormat": "Host2 ARP On" },
    { "expr": "m_host2_ping_status", "legendFormat": "Host2 Ping Host1" },
    {
     "expr": "m_host2_snmp_mac_status",
     "legendFormat": "Host2 Contains Switch MAC Address"
    },
    { "expr": "m_host2_has_host1_arp", "legendFormat": "Host2 Contains Host1 IP" },
    {
     "expr": "m_host2_snmp_mac_status2",
     "legendFormat": "Host2 Contains Switch2 MAC Address"
    }
   ]
  },
  {
   "title": "SNMP Exporter Debugger",
   "type": "state-timeline",
   "description": "SNMP Exporter Metrics Correlation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "HOSTA_SNMP_ON", "legendFormat": "Host1 SNMP Exporter Running" },
    {
     "expr": "SWITCH_HOSTA_MAC",
     "legendFormat": "Switch1 Contains Host1 Mac Address"
    },
    {
     "expr": "SWITCH2_HOSTA_MAC",
     "legendFormat": "Switch2 Contains Host1 Mac Address"
    },
    { "expr": "HOSTB_SNMP_ON", "legendFormat": "Host2 SNMP Exporter Running" },
    {
     "expr": "SWITCH_HOSTB_MAC",
     "legendFormat": "Switch1 Contains Host2 MAC Address"
    },
    {
     "expr": "SWITCH2_HOSTB_MAC",
     "legendFormat": "Switch2 Contains Host2 Mac Address"
    }
   ]
  },
  {
   "title": "Node Exporter Debugger",
   "type": "state-timeline",
   "description": "Node Exporter Status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "m_host1_node_on", "legendFormat": "Host1 Node Exporter" },
    { "expr": "m_host2_node_on", "legendFormat": "Host2 Node Exporter" }
   ]
  },
  {
   "title": "Layer 2 Debugging Summary",
   "type": "text",
   "description": "Summary of Layer 2 Debugging Script Results",
   "gridPos": { "h": 9, "w": 11, "x": 7, "y": 31 },
   "options": {
    "content": "| Action                 |             Status |\n| ----------------------:| ----------------------------:|\n| Debug Script Online | &check; |\n| Ping To Remote Host  | &check; |\n| Remote Host Exists In ARP Table | &check; |\n| Remote Host MAC Address Obtained  | &check; |\n| Remote Host Interface Obtained  | &check; |\n| Remote Host MAC Address Exists in Switch 1 MAC Address Table | &check; |\n| Remote Host MAC Address Exists in Switch 2 MAC Address Table | &#10006; |"
   }
  }
 ]
}