{
 "title": "DASHTITLE",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(sysUpTime, job)" } },
   {
    "name": "index",
    "label": "interface",
    "query": {
     "query": "query_result(ifIndex{job=~\"$job\",instance=\"$instance\"})"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Visualization",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "graph LR\n      subgraph h1 [\"Host 1\"]\n      style h1 fill:#575757\n      ip{{IP: DATAPLANEIPA}}\n      e(IFNAMEHOSTA)\n      end\n      e(IFNAMEHOSTA) ------- s1if1[NAMEIFSWITCHA]\n      subgraph s1 [\"Switch 1\"]\n      style s1 fill:#757575\n      s1ip{{IP: IPSWITCH}}\n      subgraph if [\"Interfaces\"]\n      s1if1[NAMEIFSWITCHA]\n      s1if2[NAMEIFSWITCHB]\n      end\n      end\n      s1if2[NAMEIFSWITCHB] ------- e2(IFNAMEHOSTB)\n      subgraph h2 [\"Host 2\"]\n      style h2 fill:#575757\n      ip2{{IP: DATAPLANEIPB}}\n      e2(IFNAMEHOSTB)\n      end"
   }
  },
  { "title": "Host 1", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 16 }, "options": { "content": " " } },
  { "title": "Network Element (Switch)", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 16 }, "options": { "content": " Dell S4810 Switch" } },
  { "title": "Host 2", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 16 }, "options": { "content": "Host 2 " } },
  { "title": "Flow Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "IP Address",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "options": { "content": "<center> IPHOSTA </center>" },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP Address",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "options": { "content": "<center> IPSWITCH </center>" },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP Address",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "options": { "content": "<center> IPHOSTB </center>" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Switch Interface Status",
   "type": "table-old",
   "description": "Switch Interfaces, MAC Address, MTU, and Operational State",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(ifIndex{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifName{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifName)"
    },
    {
     "expr": "sum(ifType_info{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifType)"
    },
    {
     "expr": "sum(ifPhysAddress{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex,ifPhysAddress)"
    },
    {
     "expr": "sum(ifMtu{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    },
    {
     "expr": "sum(ifOperStatus{job=~\"$job\",instance=\"IPSWITCH\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}) by (ifIndex)"
    }
   ]
  },
  {
   "title": "Host 1 Interface Status",
   "type": "table",
   "description": "MAC Address, Interface Name, Operational Status, MTU Setting",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "node_network_info{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=~\"IFNAMEHOSTA\"}"
    },
    {
     "expr": "node_network_mtu_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 2 Interface Status",
   "type": "table",
   "description": "MAC Address, Interface Name, Operational Status, MTU Setting",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "node_network_info{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}"
    },
    {
     "expr": "node_network_mtu_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}"
    }
   ]
  },
  {
   "title": "Host 1 Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=~\"IFNAMEHOSTA\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    }
   ]
  },
  {
   "title": "Switch Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}[5m])*8",
     "legendFormat": "in {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Host 2 Bandwidth In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    }
   ]
  },
  {
   "title": "Host 1 Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\",device=\"IFNAMEHOSTA\"}[5m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}[5m])*8",
     "legendFormat": "out {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Host 2 Bandwidth Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[5m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Host 1 Octets In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}[10m])",
     "legendFormat": "recv {{device}}"
    }
   ]
  },
  {
   "title": "Switch Octets In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"$job\", ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}[10m])",
     "legendFormat": "in {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Host 2 Octets In",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[10m])",
     "legendFormat": "recv {{device}}"
    }
   ]
  },
  {
   "title": "Host 1 Octets Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTA:PORTA\", device=\"IFNAMEHOSTA\",job=\"$Job\"}[10m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Octets Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\", ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}[15m])",
     "legendFormat": "out {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Host 2 Octets Out",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[10m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  { "title": "Flow Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Host 1 TCP In / Out",
   "type": "graph",
   "description": "Host 1 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 2 TCP In / Out",
   "type": "graph",
   "description": "Host 2 TCP In / Out Collected by Node Exporter",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "Host 1 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 1",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance='IPHOSTA:PORTA',job=\"$Job\"}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 2 TCP Errors",
   "type": "graph",
   "description": "Collected from the Node Exporter on Host 2",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance='IPHOSTB:PORTB',job=\"$Job\"}[5m])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    }
   ]
  },
  {
   "title": "Host 1 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 2 TCP Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "Host 1 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 2 TCP SynCookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "counter out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "Host 1 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 2 TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "Host 1 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 2 ARP Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_arp_entries{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}",
     "legendFormat": "{{ device }} - ARP entries"
    }
   ]
  },
  {
   "title": "Host 1 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\", device=\"IFNAMEHOSTA\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Host 2 Interface Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "pps", "label": "packets out (-) / in (+)" }
   ],
   "targets": [
    { "legendFormat": "{{device}} - Receive errors" },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\", device=\"IFNAMEHOSTB\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  { "title": "Element Background Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Host 1 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 1 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 1",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) /  count(count(node_cpu_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 2 CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together in Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host 2 Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average) for Host 2",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) /  count(count(node_cpu_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Host 1 RAM Used",
   "type": "gauge",
   "description": "Host 1 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} * 100) / node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})"
    }
   ]
  },
  {
   "title": "Host 1 SWAP Used",
   "type": "gauge",
   "description": "Host 1 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}) / (node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 2 RAM Used",
   "type": "gauge",
   "description": "Host 2 Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} * 100) / node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})"
    }
   ]
  },
  {
   "title": "Host 2 SWAP Used",
   "type": "gauge",
   "description": "Host 2 Used Swap",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}) / (node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Host 1 CPU Load",
   "type": "graph",
   "description": "Host 1 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 2 CPU Load",
   "type": "graph",
   "description": "Host 2 CPU Load (System, User, I/O Wait, IRQs, Idle, Other)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Host 1 Memory Load",
   "type": "graph",
   "description": "Host 1 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_MemFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - (node_memory_Cached_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTA:PORTA\",job=\"$Job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 2 Memory Load",
   "type": "graph",
   "description": "Host 2 Basic memory usage (RAM Total, Used, Cache, Buffer, Free, SWAP)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_MemFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - (node_memory_Cached_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} + node_memory_Buffers_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"} - node_memory_SwapFree_bytes{instance=\"IPHOSTB:PORTB\",job=\"$Job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Host 1 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 2 Process Schedule Stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Host 1 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Host 2 Hardware Temperature Monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 175 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Switch Total In",
   "type": "singlestat",
   "description": "Switch Dell S4810 Total In ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 186 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch Total Out",
   "type": "singlestat",
   "description": "Switch Dell S4810 Total Out",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 186 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch Max In (Current)",
   "type": "singlestat",
   "description": "Switch Dell S4810 Max In (Current)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 186 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Switch Max Out (Current)",
   "type": "singlestat",
   "description": "Switch Dell S4810 Max Out (Current)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 186 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Switch Incoming VLAN Packets",
   "type": "graph",
   "description": "Dell S4810 Switch Incoming VLAN Packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f10IfInVlanPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Outgoing VLAN Packets",
   "type": "graph",
   "description": "Dell S4810 Switch Outgoing VLAN Packets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "f10IfOutVlanPkts{ifIndex=~\"IFINDEXSWITCHHOSTB|IFINDEXSWITCHHOSTA\"}"
    }
   ]
  },
  {
   "title": "Host 1 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 2 Netstat IP In / Out Octets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "short", "label": "octects out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "Host 1 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 2 ICMP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    }
   ]
  },
  {
   "title": "Host 1 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 2 ICMP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 217 },
   "yaxes": [
    { "format": "short", "label": "messages out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    }
   ]
  },
  {
   "title": "Host 1 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 2 UDP In / Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 227 },
   "yaxes": [
    { "format": "short", "label": "datagrams out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "Host 1 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"IPHOSTA:PORTA\",job=\"$Job\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  },
  {
   "title": "Host 2 UDP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"IPHOSTB:PORTB\",job=\"$Job\"}[5m])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  }
 ]
}