## SECTION 1 GENERAL INFORMATION ##
flow: "rtmon-2023-05-05-18-02-52"
title: "PlaceholderArbitraryTitle" 
grafana_host: "http://dev2.virnao.com:3000"
pushgateway: "http://dev2.virnao.com:9091"
grafana_api_token: 

## Section 2 Hosts & Switches all under nodes ##
node:
  - name: "k8s-gen4-02.sdsc.optiputer.net"
    type: "host"
    arp: 'on'
    runtime: 610
    interface:
      - name: 
        vlan: 'not used'
      - name: "sn3700_s0"
        vlan: 3911
        peer: 
        - name: 
          interface: 
          vlan: 3911

  - name: "sn3700_s0"
    type: "switch"
    runtime: 610
    interface:
      - name: "Ethernet108"
        vlan: 3911
        peer:
        - name: "k8s-gen4-02.sdsc.optiputer.net"
          interface: 
          vlan: 3911

      - name: "PortChannel501"
        vlan: 3911
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel502"
          vlan: 'not_used'


  - name: "aristaeos_s0"
    type: "switch"
    runtime: 610
    interface:
      - name: "Port-Channel501"
        vlan: 3911
        peer:
        - name: "dellos9_s0"
          interface: "Port-channel_103"
          vlan: 'not_used'

      - name: "Port-Channel502"
        vlan: 3911
        peer:
        - name: "sn3700_s0"
          interface: "PortChannel501"
          vlan: 'not_used'


  - name: "dellos9_s0"
    type: "switch"
    runtime: 610
    interface:
      - name: "hundredGigE_1-31"
        vlan: 3911
        peer:
        - name: 
          interface: 
          vlan: 

      - name: "Port-channel_103"
        vlan: 3911
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel501"
          vlan: 'not_used'


