## SECTION 1 GENERAL INFORMATION ##
title: 
flow: 
flow_uuid: "4b9dce66-b50e-4e75-ac83-4b2e83e1d93c"
host_ip: 
grafana_host: 
pushgateway: 
grafana_api_token: 

## Section 2 Hosts & Switches all under nodes ##
node:
  - name: "T2_US_Caltech_Test:sandie-1.ultralight.org"
    type: "host"
    interface:
      - name: "mlx4p2s1"
        vlan: 'not used'
        ip: 10.251.87.10
        ping: 
      - name: "T2_US_Caltech_Test:dellos9_s0"
        vlan: 3873
        peer: 
        - name: 
          interface: 
          vlan: 3873

  - name: "T2_US_SDSC:k8s-gen4-02.sdsc.optiputer.net"
    type: "host"
    interface:
      - name: "enp65s0np0"
        vlan: 'not used'
        ip: 10.251.87.11
        ping: 
      - name: "T2_US_SDSC:sn3700_s0"
        vlan: 3873
        peer: 
        - name: 
          interface: 
          vlan: 3873

  - name: "sn3700_s0"
    type: "switch"
    interface:
      - name: "Ethernet108"
        vlan: 3911
        peer:
        - name: 
          interface: 
          vlan: 

      - name: "PortChannel501"
        vlan: 3911
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel502"
          vlan: 'not_used'


  - name: "aristaeos_s0"
    type: "switch"
    interface:
      - name: "Port-Channel501"
        vlan: 3911
        peer:
        - name: "dellos9_s0"
          interface: "Port-channel_103"
          vlan: 'not_used'

      - name: "Port-Channel502"
        vlan: 3911
        peer:
        - name: "sn3700_s0"
          interface: "PortChannel501"
          vlan: 'not_used'


  - name: "dellos9_s0"
    type: "switch"
    interface:
      - name: "hundredGigE_1-31"
        vlan: 3911
        peer:
        - name: 
          interface: 
          vlan: 

      - name: "Port-channel_103"
        vlan: 3911
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel501"
          vlan: 'not_used'


  - name: "T2_US_Caltech_Test:dellos9_s0"
    type: "switch"
    interface:
      - name: "hundredGigE_1-10"
        vlan: 3873
        peer:
        - name: "T2_US_Caltech_Test:sandie-1.ultralight.org"
          interface: "mlx4p2s1"
          vlan: 3873

      - name: "Port-channel_103"
        vlan: 3873
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel501"
          vlan: 'not_used'


  - name: "T2_US_SDSC:sn3700_s0"
    type: "switch"
    interface:
      - name: "Ethernet108"
        vlan: 3873
        peer:
        - name: "T2_US_SDSC:k8s-gen4-02.sdsc.optiputer.net"
          interface: "enp65s0np0"
          vlan: 3873

      - name: "PortChannel501"
        vlan: 3873
        peer:
        - name: "aristaeos_s0"
          interface: "Port-Channel502"
          vlan: 'not_used'


  - name: "NRM_CENIC:aristaeos_s0"
    type: "switch"
    interface:
      - name: "Port-Channel502"
        vlan: 3873
        peer:
        - name: "sn3700_s0"
          interface: "PortChannel501"
          vlan: 'not_used'

      - name: "Port-Channel501"
        vlan: 3873
        peer:
        - name: "dellos9_s0"
          interface: "Port-channel_103"
          vlan: 'not_used'


