## SECTION 1 GENERAL INFORMATION ##
switchNum: 1
hostIP: 198.32.43.15
pushgatewayPort: 9091 
grafanaHostIP: 'sense-mon.es.net'
hostA:
  IP: 198.32.43.16
hostB:
  IP: 198.32.43.15
configFile: "config.yml"

## SECTION 2 SNMP EXPORTERS ##
snmpMetricsA:
  SNMPHostIP: 198.32.43.16
  target: 172.16.1.1
  portIn: 
    ifName: 'hundredGigE 1/27'
    ifVlan: 'Vlan 1000'
  portOut:
    ifName: 'hundredGigE 1/31'
    ifVlan: 'Vlan 1000'
  oids: [dot1dTpFdbAddress, ifMIB, ifMtu, ifName, ifOperStatus, ifPhysAddress, ifIndex, ifType, f10IfInVlanPkts, f10IfOutVlanPkts]
  communityString: "COMMUNITYSTRING" # keep the quotation marks only replace COMMUNITYSTRING
  scrapeTimeout: 5s
  retries: 3

## SECTION 3 ARP and TCP EXPORTERS ##
arpMetrics:
  port: 9192
  scrapeDuration: 900
  scrapeInterval: 30

tcpMetrics:
  port: 9191 # Site
  # Collect all packets continuously over the scrape interval
  # Not recommended for general use cases, but provides additional information if set to True
  # Defaults to False, collects the most recent burst (1 second's worth of data) at the current scrape interval
  continuousCollect: False
  scrapeDuration: 900
  scrapeInterval: 30