## SECTION 1 GENERAL INFORMATION ##
switchNum: 1
dashTitle: "Top Flow Dashboard"
debugTitle: "Top Flow L2 Debugging Dashboard"
flow: " flow 1 "
hostIP:  172.31.72.189 # example 198.32.43.16
# The DNS of the host which is running the Grafana container
grafanaHostIP: 'dev2.virnao.com'
grafanaPort: 3000 # Do not change unless container mapping change
pushgatewayPort: 9091 # Do not change unless container mapping change
grafanaAPIToken: "CONFIG"
configFile: "config.yml"

hostA: # Host 1
  IP: 198.32.43.16 #ucsd_cluster1
  interfaceName: 'ens2f0np0.1000'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/27'
    ifVlan: 'Vlan 1000' 
    order: 1

hostB: # Host 2
  IP: 198.32.43.15 #ucsd_cluster2
  interfaceName: 'ens2f0.1000' # need, could be vlan.number something random ens2|vlan.100
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  switchPort: 
    ifName: 'hundredGigE 1/31'
    ifVlan: 'Vlan 1000'
    order: 4

## SECTION 2 SWITCH INFORMATION ##
switchDataA:
  job_name: 'snmp1'
  SNMPHostIP: 198.32.43.16
  target: 172.16.1.1
  # switch if format: " - IF: optional" 
  switchif: "" # optional
  portIn:
    ifName: 'hundredGigE 1/27'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 2

  portOut:
    ifName: 'hundredGigE 1/31'
    vlan: 1000
    ifVlan: 'Vlan 1000'
    order: 3

## SECTION 3 TCP and ARP (possible more in the future) ##
arpMetrics:
  port: 9192
  job_name: 'arpmetrics'

tcpMetrics:
  port: 9191
  job_name: 'tcpmetrics'
