apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: snmp-exporter
  name: snmp-exporter
spec:
  ports:
    - name: "9116"
      port: 9116
      targetPort: 9116
  selector:
    io.kompose.service: snmp-exporter
status:
  loadBalancer: {}
