apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: snmp-exporter
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snmp-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: snmp-exporter
    spec:
      containers:
        - env:
            - name: COMMUNITY_STRING
              value: public
            - name: MYIP
              value: ucsd_cluster
            - name: OIDS_LIST
              value: '["ifMIB", "ifMtu", "ifName", "ifPhysAddress", "ifIndex", "ifType"]'
            - name: PRIVATE_MIB
              value: dell
            - name: PUSHGATEWAY_SERVER
              value: dev2.virnao.com:9091
            - name: RETRY
              value: "3"
            - name: SNMP_PORT
              value: "9116"
            - name: SWITCH_TARGET
              value: 132.249.2.46
            - name: TIMEOUT
              value: 5s
          image: zhenboyan/rocky_snmp_exporter:latest
          name: snmp-exporter
          ports:
            - containerPort: 9116
          resources: {}
      restartPolicy: Always
status: {}
