{
 "title": "Multi Switch Flow Dashboard |Flow: UNIQUE_GLOBAL_ID| 03/08_12:38",
 "description": "Simple End-to-End Flow Monitoring Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "End-to-End Flow Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "End-to-End Flow Topology", "type": "jdbranham-diagram-panel", "gridPos": { "h": 24, "w": 24, "x": 0, "y": 1 }, "options": { "content": "INSERTTOPOLOGY" } },
  {
   "title": "Host Flow Summary - sdn-dtn-2-10.ultralight.org",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "sdn-dtn-2-10.ultralight.org - Node Interface Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 200 },
   "options": {
    "content": "```\nHost: sdn-dtn-2-10.ultralight.org   Interface: [{'name': 'ens2f0np0.3911', 'vlan': 'not used', 'ip': '10.251.86.10', 'ping': '10.251.86.12'}, {'name': 'hundredGigE 1/31', 'vlan': 'not used', 'peer': [{'name': 'Caltech LRT-SDN-R02-Dell-Z9100', 'interface': 'hundredGigE 1/31', 'vlan': 'not used'}]}]\n ```"
   }
  },
  {
   "title": "sdn-dtn-2-10.ultralight.org - interface: ens2f0np0.3911 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"10.251.86.10\", device=\"ens2f0np0.3911\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"10.251.86.10\",device=\"ens2f0np0.3911\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - Caltech LRT-SDN-R02-Dell-Z9100",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 }
  },
  {
   "title": "Caltech LRT-SDN-R02-Dell-Z9100 - Node Interface Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 203 },
   "options": {
    "content": "```\nSwitch: Caltech LRT-SDN-R02-Dell-Z9100   Interface: [{'name': 'hundredGigE 1/31', 'vlan': 'not used', 'peer': [{'name': 'sdn-dtn-2-10.ultralight.org', 'interface': 'hundredGigE 1/31', 'vlan': 'not used'}]}, {'name': 'Port-channel 103', 'vlan': 'not used', 'peer': [{'name': 'UCSD SN3700', 'interface': 'PortChannel501', 'vlan': 'not used'}]}]\n ```"
   }
  },
  {
   "title": "Caltech LRT-SDN-R02-Dell-Z9100 - interface: hundredGigE 1/31 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Caltech LRT-SDN-R02-Dell-Z9100 - interface: Port-channel 103 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Switch Flow Summary - UCSD SN3700",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 }
  },
  {
   "title": "UCSD SN3700 - Node Interface Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 208 },
   "options": {
    "content": "```\nSwitch: UCSD SN3700   Interface: [{'name': 'PortChannel501', 'vlan': 'not used', 'peer': [{'name': 'Caltech LRT-SDN-R02-Dell-Z9100', 'interface': 'Port-channel 103', 'vlan': 'not used'}]}, {'name': 'etp28', 'vlan': 'not used', 'peer': [{'name': 'k8s-gen4-01.sdsc.optiputer.net', 'interface': 'etp28', 'vlan': 'not used'}]}]\n ```"
   }
  },
  {
   "title": "UCSD SN3700 - interface: PortChannel501 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "UCSD SN3700 - interface: etp28 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "recv {{ifDescr}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifIndex=~\"DYNAMICIFINDEX\"}[1m])*8",
     "legendFormat": "trans {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Host Flow Summary - k8s-gen4-02.sdsc.optiputer.net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 }
  },
  {
   "title": "k8s-gen4-02.sdsc.optiputer.net - Node Interface Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 213 },
   "options": {
    "content": "```\nHost: k8s-gen4-02.sdsc.optiputer.net   Interface: [{'name': 'vlan.3911', 'vlan': 'not used', 'ip': '10.251.86.12', 'ping': '10.251.86.10'}, {'name': 'etp28', 'vlan': 'not used', 'peer': [{'name': 'SN3700', 'interface': 'etp28', 'vlan': 'not used'}]}]\n ```"
   }
  },
  {
   "title": "k8s-gen4-02.sdsc.optiputer.net - interface: vlan.3911 Flow Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "Bps", "label": "bw out(-) / in(+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{exported_instance=\"10.251.86.12\", device=\"vlan.3911\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{exported_instance=\"10.251.86.12\",device=\"vlan.3911\"}[1m])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  }
 ]
}