name: Trigger Secret Scan from Fork

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  get_diff:
    runs-on: ubuntu-latest
    outputs:
      files_csv: ${{ steps.get.outputs.files_csv }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get changed files
      id: get
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          BASE_REF="${{ github.event.before }}"
          HEAD_REF="${{ github.event.after }}"
        else
          BASE_REF="origin/${{ github.event.pull_request.base.ref }}"
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          HEAD_REF=FETCH_HEAD
        fi

        echo "Base: $BASE_REF"
        echo "Head: $HEAD_REF"

        git diff --name-only "$BASE_REF" "$HEAD_REF" > file_list.txt
        FILES_CSV=$(paste -sd, file_list.txt)

        {
          echo "files_csv<<EOF"
          echo "$FILES_CSV"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

  prepare-and-call:
    needs: get_diff
    uses: ./.github/workflows/trusted-scan.yaml
    with:
      changed_files: ${{ needs.get_diff.outputs.files_csv }}
    secrets:
      AIAPIKEY: ${{ secrets.AIAPIKEY }}
      AIAPIURL: ${{ secrets.AIAPIURL }}
